config/routes.rb
Rails.application.routes.draw do
  resources :recipe_ingredients
  resources :allergies
  resources :recipes
  resources :ingredients
  resources :users, only: [:new, :create, :edit, :update, :show, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/allergy.rb
class Allergy < ApplicationRecord
  belongs_to :user
  belongs_to :ingredient
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :allergies, dependent: :destroy
  has_many :users, through: :allergies
  has_many :recipe_ingredients, dependent: :destroy
  has_many :recipes, through: :recipe_ingredients
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
  has_many :recipe_ingredients, dependent: :destroy
  has_many :ingredients, through: :recipe_ingredients
  accepts_nested_attributes_for :ingredients
end

app/models/recipe_ingredient.rb
class RecipeIngredient < ApplicationRecord
  belongs_to :recipe
  belongs_to :ingredient
end

app/models/user.rb
class User < ApplicationRecord
  has_many :recipes, dependent: :destroy
  has_many :allergies, dependent: :destroy
  has_many :ingredients, through: :allergies

  def name
    self.first_name + " " + self.last_name
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController

  before_action :get_ingredient, only: :show

  def index
    @ingredients = Ingredient.all
  end

  def show
  end

  private

  def get_ingredient
    @ingredient = Ingredient.find(params[:id])
  end

end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController


  before_action :get_recipe, only: [:show, :edit, :update, :destroy]

  def index
    @recipes = Recipe.all
  end

  def new
    @recipe = Recipe.new
    @users = User.all
    @ingredients = Ingredient.all
  end

  def create
    @recipe = Recipe.create(recipe_params)
    ids = params[:recipe][:ingredient_ids].select { |id| !id.empty?}
    ids.each do |id|
      @recipe.ingredients << Ingredient.find(id)
    end
    redirect_to recipe_path(@recipe)
  end

  def show
  end

  def edit
    @users = User.all
    @ingredients = Ingredient.all
  end

  def update
    @recipe.update(recipe_params)
    redirect_to recipe_path(@recipe)
  end

  def destroy
    @recipe.destroy
    redirect_to recipes_path
  end


  private

  def get_recipe
    @recipe = Recipe.find(params[:id])
  end

  def recipe_params
    params.require(:recipe).permit(:name, :user_id, :ingredient_ids)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
end

app/helpers/allergies_helper.rb
module AllergiesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/helpers/recipe_ingredients_helper.rb
module RecipeIngredientsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/ingredients/index.html.erb
<h1>Ingredients Index</h1>
<%ingredients = @ingredients.sort_by { |ingredient| -ingredient.allergies.count }%>
<%ingredients.each do |ingredient|%>
<ul>
<li><%=link_to ingredient.name, ingredient_path(ingredient)%> | Number of allergies: <%=ingredient.allergies.count%></li>
</ul>
<%end%>

app/views/ingredients/show.html.erb
<h1><%=@ingredient.name%></h1>
<h3>Recipes having this ingredient:</h3>
<%@ingredient.recipes.each do |recipe|%>
<ul>
<li><%=recipe.name%></li>
</ul>
<%end%>
<%=button_to "Go back to ingredients index", ingredients_path, method: :get%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AllergensLab</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/recipes/_recipes_form.html.erb
<%= form_for @recipe do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <br>
  <%= f.label "User: " %>
  <%= f.collection_select(:user_id, @users, :id, :name) %>
  <br>
  <%= f.label "Ingredients (select multiple): " %>
  <%= f.collection_select(:ingredient_ids, @ingredients, :id, :name, {}, {multiple: true}) %>
  <%= f.submit %>
  <% end %>

app/views/recipes/edit.html.erb
<h1>Edit Recipe</h1>

<%= render "recipes_form" %>

app/views/recipes/new.html.erb
<h1>New Recipe Form</h1>

<%= render "recipes_form" %>

app/views/recipes/show.html.erb
<h1><%= @recipe.name %></h1>

<h2>Created By: <%= link_to @recipe.user.name, user_path(@recipe.user) %></h2>
<h2>Ingredients: </h2>
<ul>
  <% @recipe.ingredients.each do |ingredient| %>
    <li><%= link_to ingredient.name, ingredient_path(ingredient) %></li>
  <% end %>
</ul>

app/views/users/show.html.erb
<h1><%= @user.name %></h1>
<h3>Allergies: </h3>
  <% if @user.ingredients != nil || @user.ingredients != [] %>
    <ul>
      <% @user.ingredients.each do |ingredient| %>
        <li><%= link_to ingredient.name, ingredient_path(ingredient) %></li>
      <% end %>
    </ul>
  <% else %>
    <div>None</div>
  <% end %>
<h3>Recipes: </h3>
  <% if @user.recipes != nil || @user.recipes != [] %>
    <ul>
      <% @user.recipes.each do |recipe| %>
        <li><%= link_to recipe.name, recipes_path %></li>
      <% end %>
    </ul>
  <% else %>
    <div>None</div>
  <% end %>